# Generated by Django 4.1.11 on 2023-11-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0014_sharecode_delete_githubcollaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.TextField()),
                ('classDiagram', models.TextField()),
                ('flowChart', models.TextField()),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.folderupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
            ],
        ),
    ]
