# Generated by Django 4.1.11 on 2023-11-07 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0016_alter_highlevel_classdiagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaniaBusinessLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.TextField()),
                ('file_name', models.TextField()),
                ('folder_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
            ],
        ),
    ]
